// - LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";
//APPLICATION
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_FONT = "CHANGE_FONT";
export const FORCE_APPEARANCE = "FORCE_APPEARANCE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const SET_MENU = "SET_MENU";
export const SET_INTRO = "SET_INTRO";

export const REGISTRATION="REGISTRATION";
export const REGISTRATION_SUCCESS="REGISTRATION_SUCCESS";
export const REGISTRATION_START="REGISTRATION_START";
export const REGISTRATION_ERROR="REGISTRATION_ERROR";